// manage-frontend/src/pages/dashboard/DashboardPage.tsx
/**
 * @file src/pages/dashboard/DashboardPage.tsx
 * @description 仪表盘（M2-17，Phase 5 收口）。
 *   统计卡片来自公开 GET /stats；分类分布用 recharts 环形图（StatsChart）呈现 GET /categories/stats；
 *   近期文章来自 GET /admin/articles?sort=-createdAt、近期评论来自 GET /admin/comments（editor+）。
 *   本页同时是「活体探针」：能渲染即代表代理/信封/令牌/分页整条链路存活。
 * @module manage-frontend/pages/dashboard
 * @date 2026-08-29
 * @remarks 本文件保留同一页面/表格的声明式编排，查询与操作逻辑已由 hooks 或列模块承载；为便于核对控件状态与确认流程，允许超过 200 行。
 */

import { useQuery } from '@tanstack/react-query'
import { format } from 'date-fns'
import { Eye, FileClock, FileText, MessageSquare, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { listAdminArticles } from '@/api/articles'
import { listAdminComments } from '@/api/comments'
import { StatCard } from '@/components/dashboard/StatCard'
import { StatsChart } from '@/components/dashboard/StatsChart'
import { QueryErrorState } from '@/components/feedback/QueryErrorState'
import { PageHeader } from '@/components/layout/PageHeader'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { useCategoryStats, useSiteStats } from '@/hooks/useSite'
import { canManageArticles, canModerateComments } from '@/lib/permission'
import { useAuthStore } from '@/store/auth'
import type { ArticleStatus, CommentStatus } from '@/types/common'

/** 文章状态 → 语义令牌类（与 ArticleListPage 一致）。 */
const ARTICLE_STATUS: Record<ArticleStatus, string> = {
  draft: 'bg-status-draft text-status-draft-fg',
  pending: 'bg-status-pending text-status-pending-fg',
  published: 'bg-status-published text-status-published-fg',
}
const ARTICLE_STATUS_LABEL: Record<ArticleStatus, string> = {
  draft: '草稿',
  pending: '待审',
  published: '已发布',
}
/** 评论状态 → 语义令牌类（与 CommentListPage 一致）。 */
const COMMENT_STATUS: Record<CommentStatus, string> = {
  approved: 'bg-status-approved text-status-approved-fg',
  rejected: 'bg-status-rejected text-status-rejected-fg',
  reviewing: 'bg-status-reviewing text-status-reviewing-fg',
}
const COMMENT_STATUS_LABEL: Record<CommentStatus, string> = {
  approved: '通过',
  rejected: '拒绝',
  reviewing: '复核中',
}

/** 小状态标签。 */
const StatusTag = ({ cls, label }: { cls: string; label: string }) => (
  <span className={`inline-block shrink-0 rounded px-2 py-0.5 text-xs font-medium ${cls}`}>
    {label}
  </span>
)

/** 日期格式化（与列表页一致）。 */
const formatDate = (v?: string | null) => (v ? format(new Date(v), 'yyyy-MM-dd HH:mm') : '—')

/**
 * 仪表盘。展示站点整体指标、分类分布与近期动态。
 */
const DashboardPage = () => {
  const user = useAuthStore((s) => s.user)
  const isEditor = canManageArticles(user)
  const canComments = canModerateComments(user)

  const stats = useSiteStats()
  const categories = useCategoryStats()

  // 待审文章数：editor+ 才看，只要 total（pageSize 取 1 少传数据）
  const pending = useQuery({
    queryKey: ['articles', 'admin', 'pending-count'],
    queryFn: () => listAdminArticles({ status: 'pending', pageSize: 1 }),
    enabled: isEditor,
    select: (page) => page.pagination.total,
  })

  // 近期文章 Top 5：契约 admin/articles 支持 sort，按 createdAt 倒序
  const recentArticles = useQuery({
    queryKey: ['articles', 'admin', 'recent'],
    queryFn: () => listAdminArticles({ sort: '-createdAt', pageSize: 5 }),
    enabled: isEditor,
    select: (page) => page.list,
  })

  // 近期评论 Top 5：⚠️ 契约 admin/comments 不支持 sort（仅 page/pageSize/status/articleId），
  // 取默认前 5 条，前端按 createdAt 兜底倒序，确保「近期」语义稳定、不依赖后端默认顺序。
  const recentComments = useQuery({
    queryKey: ['comments', 'admin', 'recent'],
    queryFn: () => listAdminComments({ pageSize: 5 }),
    enabled: canComments,
    select: (page) =>
      [...page.list]
        .filter((c) => Boolean(c.createdAt))
        .sort((a, b) => (b.createdAt ?? '').localeCompare(a.createdAt ?? ''))
        .slice(0, 5),
  })

  return (
    <div>
      <PageHeader
        title="仪表盘"
        description={`欢迎回来，${user?.nickname || user?.username || ''}。从这里继续写作和处理读者反馈。`}
        actions={
          <div className="flex flex-wrap gap-2">
            {isEditor && (
              <>
                <Button asChild>
                  <Link to="/articles/new">写文章</Link>
                </Button>
                <Button asChild variant="outline">
                  <Link to="/articles?status=pending">处理待审文章</Link>
                </Button>
              </>
            )}
            {canComments && (
              <Button asChild variant="outline">
                <Link to="/comments?status=reviewing">处理待复核评论</Link>
              </Button>
            )}
          </div>
        }
      />

      {stats.isError && (
        <QueryErrorState title="统计暂时无法加载" onRetry={() => stats.refetch()} />
      )}
      {pending.isError && (
        <QueryErrorState title="待审数量加载失败" onRetry={() => pending.refetch()} />
      )}
      <div
        className={`grid gap-4 sm:grid-cols-2 ${isEditor ? 'xl:grid-cols-5' : 'xl:grid-cols-4'}`}
      >
        <StatCard
          label="已发布文章"
          value={stats.data?.articleCount}
          icon={FileText}
          loading={stats.isPending}
        />
        <StatCard
          label="已通过评论"
          value={stats.data?.commentCount}
          icon={MessageSquare}
          loading={stats.isPending}
        />
        <StatCard
          label="活跃会员"
          value={stats.data?.memberCount}
          icon={Users}
          loading={stats.isPending}
        />
        <StatCard
          label="累计阅读量"
          value={stats.data?.viewTotal}
          icon={Eye}
          loading={stats.isPending}
        />
        {isEditor ? (
          <StatCard
            label="待审文章"
            value={pending.data}
            icon={FileClock}
            loading={pending.isPending}
            hint="点击查看需要处理的投稿"
            to="/articles?status=pending"
          />
        ) : null}
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-3">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">分类文章分布</CardTitle>
          </CardHeader>
          <CardContent>
            {categories.isError ? (
              <QueryErrorState onRetry={() => categories.refetch()} />
            ) : categories.isPending ? (
              <div className="h-64 w-full animate-pulse rounded-md bg-muted" />
            ) : (categories.data?.length ?? 0) === 0 ? (
              <p className="py-10 text-center text-sm text-muted-foreground">暂无分类数据</p>
            ) : (
              <StatsChart data={categories.data ?? []} />
            )}
          </CardContent>
        </Card>

        {isEditor ? (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium">近期文章</CardTitle>
            </CardHeader>
            <CardContent>
              {recentArticles.isError ? (
                <QueryErrorState onRetry={() => recentArticles.refetch()} />
              ) : recentArticles.isPending ? (
                <div className="space-y-3">
                  {[0, 1, 2, 3, 4].map((i) => (
                    <Skeleton key={i} className="h-12 w-full" />
                  ))}
                </div>
              ) : (recentArticles.data?.length ?? 0) === 0 ? (
                <p className="py-10 text-center text-sm text-muted-foreground">暂无文章</p>
              ) : (
                <ul className="space-y-3">
                  {recentArticles.data?.map((a) => (
                    <li
                      key={a.id}
                      className="flex items-start justify-between gap-3 border-b border-border/50 pb-3 last:border-0 last:pb-0"
                    >
                      <div className="min-w-0">
                        <Link
                          to={`/articles/${a.id}/edit`}
                          className="block truncate text-sm font-medium hover:underline"
                          title={a.title}
                        >
                          {a.title}
                        </Link>
                        <p className="mt-0.5 text-xs text-muted-foreground">
                          {a.categoryName ? `${a.categoryName} · ` : ''}
                          {formatDate(a.createdAt)}
                        </p>
                      </div>
                      <StatusTag
                        cls={ARTICLE_STATUS[a.status]}
                        label={ARTICLE_STATUS_LABEL[a.status]}
                      />
                    </li>
                  ))}
                </ul>
              )}
            </CardContent>
          </Card>
        ) : null}

        {canComments ? (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium">近期评论</CardTitle>
            </CardHeader>
            <CardContent>
              {recentComments.isError ? (
                <QueryErrorState onRetry={() => recentComments.refetch()} />
              ) : recentComments.isPending ? (
                <div className="space-y-3">
                  {[0, 1, 2, 3, 4].map((i) => (
                    <Skeleton key={i} className="h-12 w-full" />
                  ))}
                </div>
              ) : (recentComments.data?.length ?? 0) === 0 ? (
                <p className="py-10 text-center text-sm text-muted-foreground">暂无评论</p>
              ) : (
                <ul className="space-y-3">
                  {recentComments.data?.map((c) => (
                    <li
                      key={c.id}
                      className="flex items-start justify-between gap-3 border-b border-border/50 pb-3 last:border-0 last:pb-0"
                    >
                      <div className="min-w-0">
                        <Link
                          to={`/comments?articleId=${c.articleId}`}
                          className="block truncate text-sm hover:underline"
                        >
                          <span className="font-medium">{c.userName || '匿名'}</span>
                          <span className="text-muted-foreground">：{c.content}</span>
                        </Link>
                        <p className="mt-0.5 text-xs text-muted-foreground">
                          {formatDate(c.createdAt)}
                        </p>
                      </div>
                      <StatusTag
                        cls={COMMENT_STATUS[c.status]}
                        label={COMMENT_STATUS_LABEL[c.status]}
                      />
                    </li>
                  ))}
                </ul>
              )}
            </CardContent>
          </Card>
        ) : null}
      </div>
    </div>
  )
}

export default DashboardPage

// manage-frontend-vue/src/pages/dashboard/DashboardPage.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'
import type { DataTableColumns } from 'naive-ui'
import { NButton, NDataTable, NTag } from 'naive-ui'
import { computed, h } from 'vue'
import { RouterLink } from 'vue-router'
import { listAdminArticles } from '@/api/articles'
import { listAdminComments } from '@/api/comments'
import { getCategoryStats, getSiteStats } from '@/api/site'
import { pinia } from '@/app/pinia'
import PageHeader from '@/components/PageHeader.vue'
import { canManageArticles, canModerateComments } from '@/lib/permission'
import { useAuthStore } from '@/stores/auth'
import type { ArticleSummary, Comment } from '@/types/common'

const auth = useAuthStore(pinia)
const canArticles = computed(() => canManageArticles(auth.user))
const canComments = computed(() => canModerateComments(auth.user))
const stats = useQuery({ queryKey: ['stats'], queryFn: getSiteStats })
const categories = useQuery({ queryKey: ['category-stats'], queryFn: getCategoryStats })
const articles = useQuery({ queryKey: ['articles', 'recent'], queryFn: () => listAdminArticles({ sort: '-createdAt', pageSize: 5 }), enabled: canArticles })
const comments = useQuery({ queryKey: ['comments', 'recent'], queryFn: () => listAdminComments({ pageSize: 5 }), enabled: canComments })
const articleColumns: DataTableColumns<ArticleSummary> = [
  { title: '文章', key: 'title', render: (row) => h(RouterLink, { to: `/articles/${row.id}/edit`, class: 'table-link' }, () => row.title) },
  { title: '作者', key: 'authorName', render: (row) => row.authorName || `用户 ${row.authorId}` },
  { title: '状态', key: 'status', render: (row) => h(NTag, { size: 'small', type: row.status === 'published' ? 'success' : row.status === 'pending' ? 'warning' : 'default' }, () => ({ published: '已发布', pending: '待审核', draft: '草稿' })[row.status]) },
]
const commentColumns: DataTableColumns<Comment> = [
  { title: '评论内容', key: 'content', ellipsis: { tooltip: true } },
  { title: '作者', key: 'userName', render: (row) => row.userName || `用户 ${row.userId}` },
  { title: '状态', key: 'status', render: (row) => row.status },
]
</script>

<template>
  <section class="page-content">
    <PageHeader title="仪表盘" :description="`欢迎回来，${auth.user?.nickname || auth.user?.username || ''}。从这里继续写作和处理读者反馈。`">
      <template #actions><div class="toolbar"><NButton v-if="canArticles" type="primary" tag="a" href="/articles/new">写文章</NButton><NButton v-if="canComments" tag="a" href="/comments?status=reviewing">处理待复核评论</NButton></div></template>
    </PageHeader>
    <div class="stats-grid">
      <article v-for="item in [{label:'已发布文章',value:stats.data.value?.articleCount},{label:'已通过评论',value:stats.data.value?.commentCount},{label:'活跃会员',value:stats.data.value?.memberCount},{label:'累计阅读量',value:stats.data.value?.viewTotal}]" :key="item.label" class="content-card stat-card"><div class="stat-label">{{ item.label }}</div><div class="stat-value">{{ item.value?.toLocaleString() ?? '—' }}</div><div class="stat-note">全站实时统计</div></article>
    </div>
    <div class="dashboard-grid">
      <section class="content-card card-padding"><div class="section-heading"><h2>分类内容分布</h2></div><div v-if="categories.isPending.value" class="empty-state">正在加载…</div><div v-else class="category-bars"><div v-for="item in categories.data.value" :key="item.id" class="category-bar-row"><span>{{ item.name }}</span><div class="bar-track"><div class="bar-fill" :style="{width: `${Math.min(100, item.articleCount * 10)}%`}" /></div><b>{{ item.articleCount }}</b></div></div></section>
      <section v-if="canArticles" class="content-card card-padding"><div class="section-heading"><h2>近期文章</h2><RouterLink to="/articles">查看全部</RouterLink></div><NDataTable :columns="articleColumns" :data="articles.data.value?.list ?? []" :loading="articles.isPending.value" :bordered="false" :single-line="false" /></section>
      <section v-if="canComments" class="content-card card-padding"><div class="section-heading"><h2>近期评论</h2><RouterLink to="/comments">查看全部</RouterLink></div><NDataTable :columns="commentColumns" :data="comments.data.value?.list ?? []" :loading="comments.isPending.value" :bordered="false" :single-line="false" /></section>
    </div>
  </section>
</template>

<style scoped>
.dashboard-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.section-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.section-heading h2{margin:0;font-size:15px}.section-heading a,.table-link{color:var(--accent)}.category-bars{display:grid;gap:14px}.category-bar-row{display:grid;grid-template-columns:minmax(70px,110px) 1fr 30px;align-items:center;gap:10px;font-size:12px}.bar-track{height:8px;overflow:hidden;border-radius:99px;background:var(--subtle)}.bar-fill{height:100%;border-radius:99px;background:var(--accent)}.category-bar-row b{text-align:right}.table-link{display:block;max-width:360px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:980px){.dashboard-grid{grid-template-columns:1fr}}
</style>
