// manage-frontend/src/pages/profile/FavoritesPage.tsx
/**
 * @file src/pages/profile/FavoritesPage.tsx
 * @description 我的收藏（member）。GET /me/favorites → ArticlePage（分页），可取消收藏（DELETE 幂等）。
 *   写后失效收藏列表，红点与计数不受影响。取消即列表移除该行。
 * @module manage-frontend/pages/profile
 * @date 2026-08-29
 */

import { format } from 'date-fns'
import { Link } from 'react-router-dom'
import { TablePagination } from '@/components/data/TablePagination'
import { QueryErrorState } from '@/components/feedback/QueryErrorState'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { useFavorites, useToggleFavorite } from '@/hooks/useMe'
import { useTableQuery } from '@/hooks/useTableQuery'
import { isApiError } from '@/lib/request'
import type { ArticleStatus } from '@/types/common'

/** 文章状态徽标 class。 */
const STATUS_CLS: Record<ArticleStatus, string> = {
  draft: 'bg-status-draft text-status-draft-fg',
  pending: 'bg-status-pending text-status-pending-fg',
  published: 'bg-status-published text-status-published-fg',
}

/** 状态中文。 */
const STATUS_LABEL: Record<ArticleStatus, string> = {
  draft: '草稿',
  pending: '待审',
  published: '已发布',
}

/** 我的收藏页。 */
const FavoritesPage = () => {
  const { page, setPage } = useTableQuery()
  const { data, isLoading, isError, error, refetch } = useFavorites({ page, pageSize: 10 })
  const toggle = useToggleFavorite()

  return (
    <Card>
      <CardHeader>
        <CardTitle>我的收藏</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        {isLoading ? (
          <p className="text-sm text-muted-foreground">加载中…</p>
        ) : isError ? (
          <QueryErrorState
            description={isApiError(error) ? error.message : undefined}
            onRetry={() => refetch()}
          />
        ) : data && data.list.length > 0 ? (
          <ul className="divide-y">
            {data.list.map((a) => (
              <li key={a.id} className="flex items-center gap-3 py-3">
                <div className="min-w-0 flex-1">
                  <Link
                    className="block truncate text-sm font-medium hover:underline"
                    to={`/articles/${a.id}/preview`}
                  >
                    {a.title}
                  </Link>
                  <div className="text-xs text-muted-foreground">
                    {a.categoryName ?? '未分类'} ·{' '}
                    {a.createdAt ? format(new Date(a.createdAt), 'yyyy-MM-dd') : '-'}
                  </div>
                </div>
                <span className={`rounded px-2 py-0.5 text-xs ${STATUS_CLS[a.status]}`}>
                  {STATUS_LABEL[a.status]}
                </span>
                <Button
                  variant="ghost"
                  size="sm"
                  disabled={toggle.isPending}
                  onClick={() => toggle.mutate({ articleId: a.id, add: false })}
                >
                  取消收藏
                </Button>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-sm text-muted-foreground">还没有收藏任何文章</p>
        )}
        {data?.pagination && (
          <TablePagination
            page={data.pagination.page}
            pageSize={data.pagination.pageSize}
            total={data.pagination.total}
            totalPages={data.pagination.totalPages}
            onPageChange={setPage}
          />
        )}
      </CardContent>
    </Card>
  )
}

export default FavoritesPage

// manage-frontend-vue/src/pages/profile/FavoritesPage.vue
<script setup lang="ts">
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { NButton, NTag, useMessage } from 'naive-ui'
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { listMyFavorites, removeFavorite } from '@/api/me'

const router=useRouter();const client=useQueryClient();const message=useMessage();const page=ref(1);const pageSize=10
const favorites=useQuery({queryKey:['me','favorites',page],queryFn:()=>listMyFavorites({page:page.value,pageSize})})
const remove=useMutation({mutationFn:removeFavorite,onSuccess:async()=>{message.success('已取消收藏');await client.invalidateQueries({queryKey:['me','favorites']})},onError:e=>message.error(e instanceof Error?e.message:'取消失败')})
</script>
<template><section class="content-card card-padding"><h2 class="section-title">我的收藏</h2><div v-if="favorites.isPending.value" class="empty-state">正在加载…</div><div v-else-if="favorites.data.value?.list.length" class="article-list"><article v-for="item in favorites.data.value.list" :key="item.id" class="article-row"><div class="article-main"><button type="button" class="article-link" @click="router.push(`/articles/${item.id}/preview`)">{{item.title}}</button><div class="article-meta">{{item.categoryName||'未分类'}} · {{item.createdAt?new Date(item.createdAt).toLocaleDateString('zh-CN'):'—'}}</div></div><NTag size="small">{{({draft:'草稿',pending:'待审',published:'已发布'})[item.status]}}</NTag><NButton size="small" quaternary type="error" :loading="remove.isPending.value" @click="remove.mutate(item.id)">取消收藏</NButton></article></div><div v-else class="empty-state">还没有收藏任何文章</div><div v-if="favorites.data.value?.pagination" class="pagination"><span>共 {{favorites.data.value.pagination.total}} 条</span><div><NButton :disabled="page<=1" @click="page--">上一页</NButton><NButton :disabled="page>=favorites.data.value.pagination.totalPages" @click="page++">下一页</NButton></div></div></section></template>
<style scoped>.section-title{margin:0 0 12px;font-size:17px}.article-list{display:grid}.article-row{display:flex;align-items:center;gap:12px;border-bottom:1px solid var(--line);padding:14px 0}.article-main{min-width:0;flex:1}.article-link{overflow:hidden;border:0;background:none;padding:0;color:var(--accent);text-align:left;text-overflow:ellipsis;white-space:nowrap;cursor:pointer;font-weight:600}.article-meta{margin-top:5px;color:var(--muted);font-size:12px}.pagination{display:flex;align-items:center;justify-content:space-between;margin-top:16px;color:var(--muted);font-size:12px}.pagination div{display:flex;gap:8px}</style>
